"""Начальный реестр стран и источников."""

COUNTRIES = [
    {"code": "US", "name_ru": "США", "name_en": "United States"},
    {"code": "UK", "name_ru": "Великобритания", "name_en": "United Kingdom"},
    {"code": "FR", "name_ru": "Франция", "name_en": "France"},
    {"code": "DE", "name_ru": "Германия", "name_en": "Germany"},
    {"code": "ES", "name_ru": "Испания", "name_en": "Spain"},
    {"code": "EU", "name_ru": "Европейский союз", "name_en": "European Union"},
    {"code": "QA", "name_ru": "Катар", "name_en": "Qatar"},
    {"code": "CN", "name_ru": "Китай", "name_en": "China"},
    {"code": "JP", "name_ru": "Япония", "name_en": "Japan"},
    {"code": "SG", "name_ru": "Сингапур", "name_en": "Singapore"},
    {"code": "IN", "name_ru": "Индия", "name_en": "India"},
    {"code": "SA", "name_ru": "Саудовская Аравия", "name_en": "Saudi Arabia"},
    {"code": "AE", "name_ru": "ОАЭ", "name_en": "United Arab Emirates"},
    {"code": "IL", "name_ru": "Израиль", "name_en": "Israel"},
    {"code": "ZA", "name_ru": "ЮАР", "name_en": "South Africa"},
    {"code": "AF", "name_ru": "Африка (регион)", "name_en": "Africa"},
]

# name, base_url, country_code, rss_url (если известен публичный RSS)
SOURCES = [
    # США
    ("The New York Times", "https://www.nytimes.com", "US", None),
    ("The Washington Post", "https://www.washingtonpost.com", "US", None),
    ("The Wall Street Journal", "https://www.wsj.com", "US", None),
    ("CNN", "https://www.cnn.com", "US", "http://rss.cnn.com/rss/edition.rss"),
    ("Fox News", "https://www.foxnews.com", "US", "https://moxie.foxnews.com/google-publisher/latest.xml"),
    ("NBC News", "https://www.nbcnews.com", "US", "https://feeds.nbcnews.com/nbcnews/public/news"),
    ("CBS News", "https://www.cbsnews.com", "US", "https://www.cbsnews.com/latest/rss/main"),
    ("ABC News", "https://abcnews.go.com", "US", "https://abcnews.go.com/abcnews/topstories"),
    ("Reuters", "https://www.reuters.com", "US", "https://www.reutersagency.com/feed/"),
    ("Associated Press", "https://apnews.com", "US", "https://rsshub.app/apnews/topics/apf-topnews"),
    ("Bloomberg", "https://www.bloomberg.com", "US", None),
    ("Politico", "https://www.politico.com", "US", "https://rss.politico.com/politics-news.xml"),
    ("Axios", "https://www.axios.com", "US", None),
    ("Forbes", "https://www.forbes.com", "US", "https://www.forbes.com/innovation/feed2/"),
    ("Business Insider", "https://www.businessinsider.com", "US", None),
    ("The Atlantic", "https://www.theatlantic.com", "US", "https://www.theatlantic.com/feed/all/"),
    ("ProPublica", "https://www.propublica.org", "US", "https://www.propublica.org/feeds/propublica/main"),
    ("Newsweek", "https://www.newsweek.com", "US", "https://www.newsweek.com/rss"),
    ("TIME", "https://time.com", "US", "https://time.com/feed/"),
    ("NPR", "https://www.npr.org", "US", "https://feeds.npr.org/1001/rss.xml"),
    # Великобритания
    ("BBC News", "https://www.bbc.com/news", "UK", "https://feeds.bbci.co.uk/news/rss.xml"),
    ("The Guardian", "https://www.theguardian.com", "UK", "https://www.theguardian.com/world/rss"),
    ("Financial Times", "https://www.ft.com", "UK", None),
    ("The Economist", "https://www.economist.com", "UK", None),
    ("Sky News", "https://news.sky.com", "UK", "https://feeds.skynews.com/feeds/rss/home.xml"),
    ("UnHerd", "https://unherd.com", "UK", "https://unherd.com/feed/"),
    ("The Spectator", "https://www.spectator.co.uk", "UK", "https://www.spectator.co.uk/feed/"),
    ("The Telegraph", "https://www.telegraph.co.uk", "UK", None),
    # Европа
    ("Euronews", "https://www.euronews.com", "EU", "https://www.euronews.com/rss?format=mrss"),
    ("France 24", "https://www.france24.com/en/", "FR", "https://www.france24.com/en/rss"),
    ("Deutsche Welle", "https://www.dw.com/en/", "DE", "https://rss.dw.com/rdf/rss-en-world"),
    ("Der Spiegel International", "https://www.spiegel.de/international/", "DE", "https://www.spiegel.de/international/index.rss"),
    ("Le Monde (English)", "https://www.lemonde.fr/en/", "FR", None),
    ("El País (English)", "https://english.elpais.com", "ES", "https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada"),
    ("EUobserver", "https://euobserver.com", "EU", "https://euobserver.com/rss"),
    # Ближний Восток / Азия
    ("Al Jazeera", "https://www.aljazeera.com", "QA", "https://www.aljazeera.com/xml/rss/all.xml"),
    ("South China Morning Post", "https://www.scmp.com", "CN", None),
    ("The Japan Times", "https://www.japantimes.co.jp", "JP", "https://www.japantimes.co.jp/feed/"),
    ("Nikkei Asia", "https://asia.nikkei.com", "JP", None),
    ("CNA", "https://www.channelnewsasia.com", "SG", "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml"),
    ("The Straits Times", "https://www.straitstimes.com", "SG", None),
    ("The Times of India", "https://timesofindia.indiatimes.com", "IN", "https://timesofindia.indiatimes.com/rssfeedmostread.cms"),
    ("The Hindu", "https://www.thehindu.com", "IN", "https://www.thehindu.com/news/international/feeder/default.rss"),
    ("Hindustan Times", "https://www.hindustantimes.com", "IN", "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml"),
    ("Arab News", "https://www.arabnews.com", "SA", "https://www.arabnews.com/rss.xml"),
    ("The National", "https://www.thenationalnews.com", "AE", None),
    ("The Jerusalem Post", "https://www.jpost.com", "IL", "https://www.jpost.com/rss/rssfeedsheadlines.aspx"),
    ("Haaretz", "https://www.haaretz.com", "IL", None),
    ("News24", "https://www.news24.com", "ZA", "https://feeds.news24.com/articles/news24/TopStories/rss"),
    ("allAfrica", "https://allafrica.com", "AF", "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf"),
]
